### ISSUE TITLE
Synchronize model of IO 'Special' between sample solutions for client and server

### ISSUE THREAD

**Issue by cgbram** [devonfw/training-devon-client#1]
For the sample solution of the js client, I needed to mock the model of the IO 'Special'. I assumed the following properties, some of which are currently calculated client side but might also be calculated on the server.

```
var mockspecials = [
    {
        "id": 101,
        "modificationCounter": 1,
        "revision": null,
        "number": 1,
        "specialName": "Happy Hour",
        "offerId": 5, // "Cola"
        "specialPrice": 9.99,
        "activeFrom": new Date(1970, 0, 1, 19, 0, 0),
        "activeTo": new Date(1970, 0, 1, 21, 0, 0),
        // added from offer
        "specialOffer" = offer.description,
        "originalPrice" = offer.price,
        // calculated
        "savings": <originalPrice - specialPrice>,
        "savingsPercentage": <calculated from savings>,
        "activeStatus": <"Active" | "Inactive">,
    }];
```

Please consider this when designing the IO on the server and/or align with me so that client and server implementations will match.

**Comment by maybeec** [comment]
Hi @cgbram, I will add the name for my servers [SpecialEntity](https://github.com/devonfw/tp-off-oasp4j/blob/reference-solution-simplepattern/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/dataaccess/api/SpecialEntity.java).
We are quite synchronous, besides the way of describing the active period. I have choosen a different entity called [WeeklyPeriod](https://github.com/devonfw/tp-off-oasp4j/blob/reference-solution-simplepattern/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/dataaccess/api/WeeklyPeriodEntity.java) to describe a weekly reoccurring period. Is it possible for you to also go for that?

**Comment by maybeec** [comment]
Please do further development on reference-solution branch to keep the original state on development branch with which the course can start the development. Thanks.
